[package]
name = "day_1"
version = "0.2.0"
authors = ["Juan Rodriguez <jrodri89@uwo.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
